export const seedData = {
  users: {
    _model: "Users",
    homer: {
      firstName: "Homer",
      lastName: "Simpson",
      email: "homer@simpson.com",
      password: "secret",
    },
    marge: {
      firstName: "Marge",
      lastName: "Simpson",
      email: "marge@simpson.com",
      password: "secret",
    },
    bart: {
      firstName: "Bart",
      lastName: "Simpson",
      email: "bart@simpson.com",
      password: "secret",
    },
    a:{
      firstName: "A",
      lastName: "A",
      email: "a@a.ie",
      password: "a",
    }
  },
  waterfalls: {
    _model: "Waterfalls",
    powerscourt: {
      name: "Powerscourt Waterfall",
      description: "Powerscourt Waterfall in Wicklow",
      latitude: 53.14620152788905,
      longitude: -6.210519267263215,
      userid: "->users.homer",
      img: "/images/powerscourt-waterfall.jpg",
    },
    iguazu: {
      name: "Iguazu Falls",
      description: "Iguazu Falls is located on the border of Argentina and Brazil.",
      latitude: -25.6953,
      longitude: -54.4367,
      userid: "->users.marge",
      img: "/images/iguazufalls.jpg",
    },
    niagara: {
      name: "Niagara Falls",
      description: "Niagara Falls is located on the border of the United States and Canada.",
      latitude: 43.0799,
      longitude: -79.0747,
      userid: "->users.bart",
      img: "/images/niagara-falls.jpg",
    },
    victoria: {
      name: "Victoria Falls",
      description: "Victoria Falls is located on the border of Zambia and Zimbabwe.",
      latitude: -17.9243,
      longitude: 25.8567,
      userid: "->users.marge",
      img: "/images/victoria-falls.jpg",
    },
  },
  POIs: {
    _model: "POIs",
    powerscourtHouse: {
      type: "Powerscourt House & Gardens",
      description: "Beautiful gardens",
      latitude: 53.184451129908986,
      longitude: -6.186072170673118,
      waterfallid: "->waterfalls.powerscourt",
      img: "/images/powerscourt-house-gardens.jpg",
    },

    attractionGargantaDoDiabo: {
      type: "Attraction",
      description: "The Garganta do Diabo (Devil’s Throat): Location: Accessible from both sides, but superior from Argentina. Type: Natural Feature.",
      latitude: -25.695225872631873,
      longitude: -54.43660026853571,
      waterfallid: "->waterfalls.iguazu",
      img: "/images/devilstroat.jpg",
    },
    hospitalTuristico: {
      type: "Hospital",
      description: "Hospital Turistico (Puerto Iguazú, Argentina): Location: Av. Victoria Aguirre 125, Puerto Iguazú. Hours: Open 8am-8pm. Type: Public Hospital.",
      latitude: -25.595943473868985,
      longitude: -54.573262479584095,
      waterfallid: "->waterfalls.iguazu",
      img: "/images/hospital-turistico.jpeg",
    },
    restaurantLaRueda: {
      type: "Restaurant",
      description: "La Rueda 1975 (Puerto Iguazú, Argentina): Location: Av. Victoria Aguirre 1975, Puerto Iguazú. Hours: 12:00 PM - 11:00 PM. Type: Casual Dining.",
      latitude: -25.60118509457849,
      longitude: -54.57171175176343,
      waterfallid: "->waterfalls.iguazu",
      img: "/images/RestauranteLaRueda1975.jpg",
    },
  },
};
